# 正式环境数据源
spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.108:3306/email_db?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: crawler
    password: crawler#@!12345
  
  redis: 
    host: 192.168.2.108
    port: 6379
    password: redis@108