# 服务配置
server:
  port: 8340
  tomcat:
    uri-encoding: UTF-8
  compression: 
    enabled: true
    
# Spring相关配置
spring:
  application:
    name: crawler-service
  profiles: 
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.6:3306/crawler_db?useUnicode=true&characterEncoding=UTF-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: crawler
    password: crawler@12345
    hikari:
      connection-test-query: select 1 from dual
  messages:
    encoding: UTF-8
  servlet: 
    multipart: 
      # 最上传文件大小
      max-file-size: 100MB
      # 最大请求数据大小
      max-request-size: 20MB
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #properties:
      #hibernate:
        #hbm2ddl:
          #auto: none
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true      
                  
  redis: 
    host: 192.168.2.6
    port: 6379
    password: redis@1234  
    timeout: 15
  # spring data
  data:
    # mongodb
    mongodb:
      host: 192.168.2.6
      port: 27017
      username: crawler
      password: test1234
      authentication-database: crawler
      database: crawler
      
# 集成MyBatis  
mybatis:   
  mapperLocations: classpath*:mybatis/mapper/**/*.xml
  typeAliasesPackage: com.efe.ms.**.model
  #configLocation: classpath:mybatis/config/mybatis-config.xml
  configuration-properties: 
    # 数据库方言
    helperDialect: mysql 
    # RowBounds参数offset作为PageNum使用 - 默认不使用
    offsetAsPageNum: true 
    # RowBounds是否进行count查询 - 默认不查询
    rowBoundsWithCount: true
    # 当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
    pageSizeZero: false
    # 分页合理化
    reasonable: false
    # 是否支持接口参数来传递分页参数，默认false
    #supportMethodsArguments: true
    #params: pageNum=pageNumKey;pageSize=pageSizeKey;  

# 日志
logging: 
  config: classpath:log-config/logback-${spring.profiles.active}.xml
  
  
  
  
  
